# Generated by Django 5.2.3 on 2025-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when item was added to cart (locked price)', max_digits=10, null=True),
        ),
    ]
